In [2]:
## 00. PyTorch Fudnamentals

import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)

2.4.0+cu121


In [3]:
## Introduction to Tensors

## Creating tensors


In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
# Vectors
vector = torch.tensor([7,7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[0,1]

tensor(8)

In [14]:
# TENSOR
TENSOR = torch.tensor([[1,2,3,4],
                        [4,5,6,4],
                        [7,8,9,4],
                        [11,12,13,4]])
TENSOR

tensor([[ 1,  2,  3,  4],
        [ 4,  5,  6,  4],
        [ 7,  8,  9,  4],
        [11, 12, 13,  4]])

In [15]:
TENSOR.ndim

2

In [16]:
TENSOR.shape
#This is saying we have 1, 3x3 tensor.

torch.Size([4, 4])

## Random Tensors
Why random tensors?

Random tensors are important because the way that many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`




In [17]:
# creating a random tensor
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0959, 0.9294, 0.9727, 0.6223],
        [0.9284, 0.1347, 0.5981, 0.3344],
        [0.8331, 0.2417, 0.6859, 0.2855]])

In [18]:
# create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size =(224,224,3)) # height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [19]:
### Zeros and Ones
# Create a tensor of all zeros
zero = torch.zeros(3,4)

In [20]:

zero * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
#tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
# this is the default data type, you can change the data type. see documentation
torch.float32

torch.float32

In [23]:
## Creating a range of tensors and tensors-like
# use torch.range()
ones_to_ten = torch.arange(0,10)
ones_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
list = range(0,10)
tensor_list = torch.tensor(list)
tensor_list

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Tensor Datatypes

**Note** Tensor Datatype is one of the 3 big errors that you will run into with Pytorch and deep learning:
1. Tensors not right dataype
2. Tensors not right shape
3. Tensors not on right device

In [25]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = ones_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
# float 32 tensor
float_32_tensor = torch.tensor([3,3,3],
                               dtype = None, #change the datatype
                               device = "cpu", # you need to have the tensor on the right device, either cpu or cuda (gpu)
                               requires_grad = False, # this tracks the mathematical changes as the deep learning algorthm adjusts
)

float_32_tensor

tensor([3, 3, 3])

In [27]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
float_32_tensor * int_32_tensor

tensor([ 9, 18, 27])

## Getting information from our tensor attributes

1. Tensors not right dataype
  a. to do get datatype from a tensor, you can use `tensor.dtype`

2. Tensors not right shape
  a. to get the shape from a tensor, you can use `tensor.shape`

3. Tensors not on right device
  a. to get device from a tensor, you can use `tensor.device`


In [28]:
# Finding details about a tensor
rand = torch.rand(3,4)
print(rand)
print(f"Datateyp of tensor: {rand.dtype}")
print(f"Shape of tensor: {rand.shape}")
print(f"Device tensor is on: {rand.device}")

tensor([[0.4388, 0.8799, 0.3686, 0.1532],
        [0.2816, 0.3867, 0.9232, 0.5654],
        [0.7539, 0.4968, 0.6850, 0.4100]])
Datateyp of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [29]:
### Manipulating Tensors (tensor operations)


tensor opporations include:
1. addition
2. subtraction
3. multiplication (element-wise)
4. division
5. matrix multiplication

In [30]:
# create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [31]:
tensor * 10

tensor([10, 20, 30])

In [32]:
# Matrix Multiplication (dot product)
torch.matmul(tensor, tensor) # use .matmul because it is so much faster

tensor(14)

In [33]:
# one of the most common errors in deep learning: shape errors
# To satisfy matrix multiplication,
#  1. the inner dimensions must match.
#  2. the resulting matrix is the shape of the outer dimensions


To fix our tensor shape issues, we can manipulate the shape of one of our tensors by using a **transpose**.

A **transpose** switches the axis or dimensions of a given tensor.

You can fix this by using the
``tensor.T``
code.

if you are interested in finding the index

```
# This is formatted as code
```

position of the largest value (max) or the index position of the smallest value (min), you would use the


`` torch.argmin(tensorname)`` or ``(tensorname).argmin()``


`` torch.argmax(tensorname)`` or ``(tensorname).argmin()`` function,

and the output will be the index  position that the max and min are located in

In [34]:
torch.argmin(rand), rand.argmin()

(tensor(3), tensor(3))

you can use the squeeze and unsqueeze functions to remove singular or add singular dimensions to a tensor

In [35]:
# working with squeeze and unsqueeze

print(f"orginal tensor: {rand}")
print(f"original tensor shape: {rand.shape}")

print(f"unsqueezed tensor: {rand.unsqueeze(dim=0)}")
print(f"unsqueezed tensor shape: {rand.unsqueeze(dim=0).shape}")

print(f"squeezed tensor: {rand.squeeze()}") #notice how this doesnt do anything because there is no single dimension in the "rand" tensor
print(f"squeezed tensor shape: {rand.squeeze().shape}")

orginal tensor: tensor([[0.4388, 0.8799, 0.3686, 0.1532],
        [0.2816, 0.3867, 0.9232, 0.5654],
        [0.7539, 0.4968, 0.6850, 0.4100]])
original tensor shape: torch.Size([3, 4])
unsqueezed tensor: tensor([[[0.4388, 0.8799, 0.3686, 0.1532],
         [0.2816, 0.3867, 0.9232, 0.5654],
         [0.7539, 0.4968, 0.6850, 0.4100]]])
unsqueezed tensor shape: torch.Size([1, 3, 4])
squeezed tensor: tensor([[0.4388, 0.8799, 0.3686, 0.1532],
        [0.2816, 0.3867, 0.9232, 0.5654],
        [0.7539, 0.4968, 0.6850, 0.4100]])
squeezed tensor shape: torch.Size([3, 4])


In [55]:
# practicing permuting tensors, where permuting changes the dimensions of a tensor

x_original = torch.rand(size = (224, 224, 3))    # height, width, color_channels
x_permuted = x_original.permute(2, 0, 1)

print(f"x_original.shape: {x_original.shape}")
print(f"x_permuted.shape: {x_permuted.shape}")

x_original.shape: torch.Size([224, 224, 3])
x_permuted.shape: torch.Size([3, 224, 224])


In [87]:
x_original[0,0,1] = 0
x_permuted = x_original.permute(2,0,1)
x_permuted

tensor([[[0.0000, 0.0000, 0.0000,  ..., 0.4674, 0.7835, 0.3802],
         [0.0000, 0.8793, 0.0000,  ..., 0.3606, 0.7551, 0.3724],
         [0.0000, 0.7656, 0.9898,  ..., 0.1995, 0.2499, 0.5861],
         ...,
         [0.5350, 0.2417, 0.7391,  ..., 0.0790, 0.1356, 0.0965],
         [0.5311, 0.8279, 0.2427,  ..., 0.2548, 0.2445, 0.4999],
         [0.8317, 0.1166, 0.1203,  ..., 0.1739, 0.6254, 0.2778]],

        [[0.0000, 0.8694, 0.7754,  ..., 0.6358, 0.5378, 0.4567],
         [0.8548, 0.1109, 0.6076,  ..., 0.4316, 0.2639, 0.8283],
         [0.7521, 0.7870, 0.3140,  ..., 0.4175, 0.8251, 0.3298],
         ...,
         [0.7806, 0.3225, 0.4640,  ..., 0.7589, 0.4476, 0.1352],
         [0.0630, 0.3099, 0.7720,  ..., 0.7312, 0.6360, 0.4469],
         [0.0833, 0.0662, 0.5346,  ..., 0.6535, 0.2979, 0.9560]],

        [[0.6938, 0.7631, 0.0021,  ..., 0.1515, 0.1000, 0.6702],
         [0.4158, 0.5057, 0.8214,  ..., 0.0205, 0.2808, 0.0295],
         [0.9789, 0.9484, 0.0857,  ..., 0.5719, 0.5403, 0.

## Indexing (selecting data from tensors)
Indexing with Pytorch is almost identical to indexing with Numpy


In [100]:
# creating a tensor
import torch #so that we can start the notebook from here next time instead of running the whole thing

x = torch.arange(1,10,1).reshape(1,3,3) #reshape works by (dimensions, row, columns)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [104]:
# lets index on the middle bracket, dimension 1

x[0,0]

tensor([1, 2, 3])

In [116]:
# now lets index on the column dimension

x[0, 1, 2]

tensor(6)